README.md
main.go

Fixes .yaml file endings and changes them to .yml. This might be a leftover from an earlier change.

Changes .yaml file ending to .yml [consistency]

---

xml/attribute_set.go
xml/element.go
xml/element_set.go
xml/element_set_test.go
xml/parser.go
xml/presence.go

I'm just going through the code base to get to know it a bit and making changes that seem useful. I hope you didn't have the struct wrappers for a reason.

xml: Remove unnecessary struct types around slices

---

module/xep0077/register.go

@ortuman 
I made a new pull request. removed LastPresenceAt

Bug fixed: register new user presence info

---

auth/scram_test.go

forgotten note for SCRAM-SHA-256

forgotten note for SCRAM-SHA-256

---

README.md
cmd/jackal/config.go
cmd/jackal/modules.go
module/xep0202/interface.go
module/xep0202/time.go
module/xep0202/time_test.go
util/xmpp/xmpp.go

Documentation here: https://xmpp.org/extensions/xep-0202.html

Add support for XEP-0202: Entity Time

---

go.mod
go.sum
pkg/c2s/in_test.go
pkg/component/xep0114/in_test.go
pkg/module/offline/offline_test.go
pkg/module/xep0199/ping_test.go
pkg/s2s/in_test.go
pkg/s2s/out_test.go
pkg/session/session.go
pkg/session/session_test.go

N/A
Update to latest stravaganza release

Upgrade to latest stravaganza release

---

pkg/c2s/in.go
pkg/component/xep0114/in.go
pkg/s2s/in.go
pkg/s2s/out.go
pkg/session/session.go

Added stream identifier to stream contextual logger

Added stream identifier to contextual logger

---

pkg/c2s/in.go
pkg/c2s/in_test.go
pkg/c2s/resource_manager.go
pkg/c2s/router_test.go
pkg/c2s/util_test.go
pkg/model/c2s/model.go
pkg/model/c2s/model_test.go
pkg/module/roster/roster_test.go
pkg/module/xep0012/last_test.go
pkg/module/xep0030/disco_test.go
pkg/module/xep0191/blocklist_test.go
pkg/module/xep0198/stream_test.go
pkg/module/xep0280/carbons_test.go

c2s
Provide c2s info via read-only interface.

Refactor c2s info model

---

CHANGELOG.md
helm/Chart.yaml
helm/values.yaml
pkg/version/version.go

0.61.0 release

---

README.md
go.mod

updated to go 1.19

---

CHANGELOG.md
pkg/hook/mam.go
pkg/module/xep0313/mam.go
pkg/module/xep0313/mam_test.go

module: added mam events

---

CHANGELOG.md
pkg/version/version.go

v0.62.1 release

---

dockerfiles/Dockerfile
scripts/dockerimage.sh

build: use golang base dockerimage

---

CHANGELOG.md
pkg/version/version.go

v0.62.2 release

---

pkg/module/xep0313/mam.go
pkg/module/xep0313/mam_test.go
pkg/module/xep0313/manager.go
pkg/module/xep0313/manager_test.go

module/xep0313: mam manager

---

pkg/c2s/in.go
pkg/s2s/in.go

s2s: override stanza on received hooks

---

CHANGELOG.md
pkg/version/version.go

v0.62.3 release

---

pkg/module/xep0313/mam.go
pkg/module/xep0313/manager.go

xep0313: mam manager refactor

---

config/example.config.yaml

Fix typo of a authentication mechanism value  in `example.config.yaml`

Fix configuration typo

---

README.md

Improve docker documentation adding required ports to expose

Improve docker documentation

---

pkg/parser/parser.go

parser
Preallocate attributes slice during XML parsing

parser: preallocate attribute slice

---

helm/Chart.yaml

updated helm chart

---

helm/values.yaml

helm: increase etcd replica count

---

helm/scripts/upgrade.sh
helm/templates/dep-jackal.yaml
helm/values.yaml

helm: fix pgsql secret misconfiguration

---

helm/templates/sts-redis.yaml

helm: make redis statefulset

---

CHANGELOG.md
go.mod
go.sum

updated to latest stavaganza release

---

CHANGELOG.md
dockerfiles/Dockerfile
helm/values.yaml
pkg/version/version.go

v0.63.0 release

---

go.mod
go.sum

update to latest stravaganza release

---

CHANGELOG.md
helm/values.yaml
pkg/version/version.go

v0.64.0 release
